package models

import (
	"time"

	"github.com/google/uuid"
)

type Billings struct {
	ID            uuid.UUID  `gorm:"type:uuid;primaryKey" json:"id"`
	UserID        uuid.UUID  `gorm:"type:uuid;not null" json:"user_id"`
	User          Users      `gorm:"foreignKey:UserID;references:ID;constraint:OnDelete:CASCADE" json:"user"`
	BillingNumber string     `gorm:"type:varchar(50);not null;comment:Running number generated by system" json:"billing_number"`
	TotalPrice    int        `gorm:"type:numeric;default:0" json:"total_price"`
	TotalQty      int        `gorm:"type:numeric;default:0" json:"total_qty"`
	Tax           int        `gorm:"type:numeric;default:0" json:"tax"`
	Discount      int        `gorm:"type:numeric;default:0" json:"discount"`
	GrandTotal    int        `gorm:"type:numeric;default:0" json:"grand_total"`
	Remark        string     `gorm:"type:text;" json:"remark"`
	Status        string     `gorm:"type:char(2);default:S1;not null;comment:S1=PENDING,S2=PAID,S3=CANCELED" json:"status"`
	Deleted       bool       `gorm:"type:boolean;default:false" json:"deleted"`
	CreatedAt     time.Time  `gorm:"type:timestamp" json:"created_at"`
	UpdatedAt     *time.Time `gorm:"type:timestamp" json:"updated_at"`
}
