// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/campaigns/analytics/dashboard/{workspace_id}/{campaign_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get line-graph for form entries for last 30days",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Campaign Analytics"
                ],
                "summary": "Form Entries Graphic",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Campaign ID",
                        "name": "campaign_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/campaigns/analytics/form_entries/{workspace_id}/{campaign_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List of form entries based on workspace and campaign",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Campaign Analytics"
                ],
                "summary": "Form Entries List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Campaign ID",
                        "name": "campaign_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page of list data",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limitting data you want to get",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Find your data with keywords",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/campaigns/analytics/form_entries/{workspace_id}/{campaign_id}/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Detail of user entry for each campaign",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Campaign Analytics"
                ],
                "summary": "Form Entry detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Campaign ID",
                        "name": "campaign_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/campaigns/dashboard/{workspace_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get summary data campaign for dashboard",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Campaigns"
                ],
                "summary": "Campaign Dashboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/campaigns/detail/{workspace_id}/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get detail of campaigns you created",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Campaigns"
                ],
                "summary": "Detail Campaigns",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/campaigns/seos/{campaign_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the list of seo campaign you created",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Campaign SEO"
                ],
                "summary": "List SEO Campaign",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Campaign ID",
                        "name": "campaign_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page of list data",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limitting data you want to get",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Find your data with keywords",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "created_at:desc",
                        "description": "Ordering data",
                        "name": "orderBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create new seo campaign data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Campaign SEO"
                ],
                "summary": "Create SEO Campaign",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Campaign ID",
                        "name": "campaign_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SEO campaign payload",
                        "name": "campaignSeoPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/masterschema.CampaignSeoPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/campaigns/seos/{campaign_id}/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get detail of seo campaign you created",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Campaign SEO"
                ],
                "summary": "Detail SEO Campaign",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Campaign ID",
                        "name": "campaign_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update existing seo campaign data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Campaign SEO"
                ],
                "summary": "Update SEO Campaign",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Campaign ID",
                        "name": "campaign_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SEO campaign payload",
                        "name": "campaignSeoPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/masterschema.CampaignSeoPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete existing seo campaign data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Campaign SEO"
                ],
                "summary": "Delete SEO Campaign",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Campaign ID",
                        "name": "campaign_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/campaigns/{workspace_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the list of campaigns you created",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Campaigns"
                ],
                "summary": "List Campaigns",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page of list data",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limitting data you want to get",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Find your data with keywords",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "created_at:desc",
                        "description": "Ordering data",
                        "name": "orderBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create new campaign data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Campaigns"
                ],
                "summary": "Create Campaign",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "campaign payload",
                        "name": "campaignPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/masterschema.CampaignPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/campaigns/{workspace_id}/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update existing campaign data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Campaigns"
                ],
                "summary": "Update Campaign",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campaign payload",
                        "name": "campaignPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/masterschema.CampaignPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete existing campaign data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Campaigns"
                ],
                "summary": "Delete Campaign",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/form_entries/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the list of history of your entries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction - Form Entry"
                ],
                "summary": "History of your entries",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page of list data",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limitting data you want to get",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Find your data with keywords",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "created_at:desc",
                        "description": "Ordering data",
                        "name": "orderBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/form_entries/history/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get detail of your curren entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction - Form Entry"
                ],
                "summary": "Detail entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of your history",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/form_entries/{campaign_id}": {
            "post": {
                "description": "Submit user value for this form",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction - Form Entry"
                ],
                "summary": "Form Entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Campaign ID",
                        "name": "campaign_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "form entry payload",
                        "name": "formEntryPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/masterschema.FormEntryPayload"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/form_entries/{campaign_key}": {
            "get": {
                "description": "Get detail form by key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction - Form Entry"
                ],
                "summary": "Preview Form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "campaign key",
                        "name": "campaign_key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/forms": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the list of forms you created",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Forms"
                ],
                "summary": "List Forms",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page of list data",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limitting data you want to get",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Find your data with keywords",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "created_at:desc",
                        "description": "Ordering data",
                        "name": "orderBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/forms/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get detail data of form you choose",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Forms"
                ],
                "summary": "Detail Form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "User login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "loginPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authschema.LoginPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Login failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get your profile detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Me"
                ],
                "summary": "Get Profile",
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/me/change_password": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Change user password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Me"
                ],
                "summary": "Change Password",
                "parameters": [
                    {
                        "description": "Change password payload",
                        "name": "changePasswordPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/meschema.ChangePasswordPayload"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Password changed"
                    },
                    "400": {
                        "description": "Failure to change password",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/me/user_profile": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update your profile data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Me"
                ],
                "summary": "Update Profile",
                "parameters": [
                    {
                        "description": "User profile payload",
                        "name": "userProfilePayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/meschema.UserProfilePayload"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Profile updated"
                    },
                    "400": {
                        "description": "Failure to update",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/register": {
            "post": {
                "description": "You can regist new user here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Registration",
                "parameters": [
                    {
                        "description": "Register credentials",
                        "name": "registerPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authschema.RegisterPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Registration success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Registration failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/store": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get store profile for logged user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store - Profile"
                ],
                "summary": "Store Profile",
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update store profile for logged user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store - Profile"
                ],
                "summary": "Update Store Profile",
                "parameters": [
                    {
                        "description": "store payload",
                        "name": "storePayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storeschema.StorePayload"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Data updated",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/store/product_categories": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the list of product categories based on logged user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store - Product Categories"
                ],
                "summary": "List Product Categories",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page of list data",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limitting data you want to get",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Find your data with keywords",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create new product category for logged user store",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store - Product Categories"
                ],
                "summary": "Create Product Category",
                "parameters": [
                    {
                        "description": "product category payload",
                        "name": "productCategoryPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storeschema.ProductCategoryPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/store/product_categories/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get detail of product category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store - Product Categories"
                ],
                "summary": "Detail Product Category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update existing product category for logged user store",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store - Product Categories"
                ],
                "summary": "Update Product Category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "product category payload",
                        "name": "productCategoryPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storeschema.ProductCategoryPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete existing product category for logged user store data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store - Product Categories"
                ],
                "summary": "Delete Product Category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/store/products": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the list of products based on logged user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store - Products"
                ],
                "summary": "List Products",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page of list data",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limitting data you want to get",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Find your data with keywords",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create new product for logged user store",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store - Products"
                ],
                "summary": "Create Product",
                "parameters": [
                    {
                        "description": "product payload",
                        "name": "productPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storeschema.ProductPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/store/products/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get detail of product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store - Products"
                ],
                "summary": "Detail Product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update existing product for logged user store",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store - Products"
                ],
                "summary": "Update Product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "product payload",
                        "name": "productPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storeschema.ProductPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete existing product for logged user store data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store - Products"
                ],
                "summary": "Delete Product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/workspaces": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the list of workspaces you created",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Workspaces"
                ],
                "summary": "List Workspaces",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page of list data",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limitting data you want to get",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Find your data with keywords",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "created_at:desc",
                        "description": "Ordering data",
                        "name": "orderBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create new workspace data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Workspaces"
                ],
                "summary": "Create Workspace",
                "parameters": [
                    {
                        "description": "Workspace payload",
                        "name": "workspacePayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/masterschema.WorkspacePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/workspaces/users/{workspace_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the list of users available in this workspace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Workspace Users"
                ],
                "summary": "List Workspace Users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page of list data",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limitting data you want to get",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Find your data with keywords",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "created_at:desc",
                        "description": "Ordering data",
                        "name": "orderBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create new user for this workspace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Workspace Users"
                ],
                "summary": "Create Workspace User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Workspace user payload",
                        "name": "workspaceUserPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/masterschema.WorkspaceUserPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/workspaces/users/{workspace_id}/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get detail data of workspace user you choose",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Workspace Users"
                ],
                "summary": "Detail Workspace User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update existing user in this workspace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Workspace Users"
                ],
                "summary": "Update Workspace User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Workspace user payload",
                        "name": "workspaceUserUpdatePayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/masterschema.WorkspaceUserUpdatePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete existing user in this workspace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Workspace Users"
                ],
                "summary": "Delete Workspace User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        },
        "/api/workspaces/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get detail data of workspace you choose",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Workspaces"
                ],
                "summary": "Detail Workspace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update existing workspace data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Workspaces"
                ],
                "summary": "Update Workspace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Workspace payload",
                        "name": "workspacePayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/masterschema.WorkspacePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete existing workspace data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master - Workspaces"
                ],
                "summary": "Delete Workspace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of your data",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request success",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    },
                    "400": {
                        "description": "Request failure",
                        "schema": {
                            "$ref": "#/definitions/commonschema.ResponseHTTP"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "authschema.LoginPayload": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "authschema.RegisterPayload": {
            "type": "object",
            "required": [
                "email",
                "fullname",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "commonschema.ResponseHTTP": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "error": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "masterschema.CampaignFormAttributePayload": {
            "type": "object",
            "required": [
                "label",
                "value"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_default": {
                    "type": "boolean",
                    "default": false
                },
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "masterschema.CampaignFormPayload": {
            "type": "object",
            "required": [
                "form_id",
                "title"
            ],
            "properties": {
                "attributes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/masterschema.CampaignFormAttributePayload"
                    }
                },
                "default_value": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "form_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_multiple": {
                    "type": "boolean",
                    "default": false
                },
                "is_required": {
                    "type": "boolean",
                    "default": false
                },
                "placeholder": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "masterschema.CampaignPayload": {
            "type": "object",
            "required": [
                "forms",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "forms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/masterschema.CampaignFormPayload"
                    }
                },
                "is_publish": {
                    "type": "boolean",
                    "default": false
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "masterschema.CampaignSeoPayload": {
            "type": "object",
            "required": [
                "access_key",
                "event",
                "platform"
            ],
            "properties": {
                "access_key": {
                    "type": "string"
                },
                "event": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                }
            }
        },
        "masterschema.FormEntryPayload": {
            "type": "object",
            "required": [
                "campaign_form_id"
            ],
            "properties": {
                "campaign_form_attribute_id": {
                    "type": "string",
                    "default": "null"
                },
                "campaign_form_id": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "masterschema.WorkspacePayload": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "is_publish": {
                    "type": "boolean",
                    "default": false
                },
                "thumbnail": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "masterschema.WorkspaceUserPayload": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string",
                    "default": "S1",
                    "maxLength": 2
                },
                "user_email": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "masterschema.WorkspaceUserUpdatePayload": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string",
                    "default": "S1",
                    "maxLength": 2
                }
            }
        },
        "meschema.ChangePasswordPayload": {
            "type": "object",
            "required": [
                "confirm_password",
                "new_password",
                "old_password"
            ],
            "properties": {
                "confirm_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "meschema.UserProfilePayload": {
            "type": "object",
            "required": [
                "first_name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "middle_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "sub_district": {
                    "type": "string"
                }
            }
        },
        "storeschema.ProductCategoryPayload": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "storeschema.ProductImages": {
            "type": "object",
            "properties": {
                "file_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "storeschema.ProductPayload": {
            "type": "object",
            "required": [
                "category_id",
                "name",
                "status"
            ],
            "properties": {
                "campaign_id": {
                    "type": "string"
                },
                "category_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storeschema.ProductImages"
                    }
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "storeschema.StorePayload": {
            "type": "object",
            "required": [
                "category",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "operational_hour": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "thumbnail": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer \" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
